"""do_not_disturb_flag

Revision ID: d25d3f0b9970
Revises: bfae164c49e1
Create Date: 2019-11-27 18:58:43.886234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25d3f0b9970'
down_revision = 'bfae164c49e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('do_not_disturb', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET do_not_disturb = true")
    op.alter_column('users', sa.Column('do_not_disturb', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'do_not_disturb')
    # ### end Alembic commands ###
